# Model arguments
model_name_or_path: glorgao/Qwen2.5-7B-SFT
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
# For definitions, see: src/h4/training/config.py
chat_template: "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
ordering_bias: 1.0
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 1000
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: qwen-2.5-7b # hub_model_id is used for querying the csv file, i.e., the curriculum.
learning_rate: 8.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: paged_adamw_32bit
output_dir: ./output/qwen-2.5-7b-uf-ob1.0-seed42
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1