# If you are slurm user, you can use this script to run the experiments in the Qwen-2.5-UF curriculum.
srun --partition=[your-partition] --time=24:00:00 --nodes=1 --ntasks-per-node=1 --gres=gpu:8 --exclusive --pty accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero2.yaml scripts/run_half.py recipes/qwen-2.5-7b-uf.yaml --curr_split=first --seed=41
srun --partition=[your-partition] --time=24:00:00 --nodes=1 --ntasks-per-node=1 --gres=gpu:8 --exclusive --pty accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero2.yaml scripts/run_half.py recipes/qwen-2.5-7b-uf.yaml --curr_split=first --seed=42
                                                                                                                                                                                                                  
srun --partition=[your-partition] --time=24:00:00 --nodes=1 --ntasks-per-node=1 --gres=gpu:8 --exclusive --pty accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero2.yaml scripts/run_half.py recipes/qwen-2.5-7b-uf.yaml --curr_split=first --seed=43
srun --partition=[your-partition] --time=24:00:00 --nodes=1 --ntasks-per-node=1 --gres=gpu:8 --exclusive --pty accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero2.yaml scripts/run_half.py recipes/qwen-2.5-7b-uf.yaml --curr_split=second --seed=41
                                                                                                                                                                                                                  
srun --partition=[your-partition] --time=24:00:00 --nodes=1 --ntasks-per-node=1 --gres=gpu:8 --exclusive --pty accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero2.yaml scripts/run_half.py recipes/qwen-2.5-7b-uf.yaml --curr_split=second --seed=42
srun --partition=[your-partition] --time=24:00:00 --nodes=1 --ntasks-per-node=1 --gres=gpu:8 --exclusive --pty accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero2.yaml scripts/run_half.py recipes/qwen-2.5-7b-uf.yaml --curr_split=second --seed=43

