# Model arguments
model_name_or_path: glorgao/Qwen2.5-7B-SFT
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# LoRA arguments
use_peft: true
load_in_4bit: false
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
# For definitions, see: src/h4/training/config.py
chat_template: "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
dataset_mixer:
  argilla/dpo-mix-7k: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 4

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 10
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: qwen-2.5-7b-argilla
learning_rate: 5.0e-5
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: paged_adamw_32bit
output_dir: ./output/qwen-2.5-7b-argilla-seed42
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "no"
seed: 42
warmup_ratio: 0.1